create table public.contact_messages (
  id bigint generated by default as identity not null,
  user_id uuid null,
  name character varying(100) not null,
  email character varying(255) null,
  device character varying(100) null,
  category character varying(50) null,
  message text not null,
  status character varying(20) not null default 'new'::character varying,
  admin_notes text null,
  user_agent text null,
  browser_info jsonb null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint inquiries_pkey primary key (id),
  constraint inquiries_user_id_fkey foreign KEY (user_id) references users (id) on delete set null
) TABLESPACE pg_default;