create table public.users (
  email text not null,
  username text null,
  provider text null,
  sign_in_time timestamp without time zone null default now(),
  id uuid not null default gen_random_uuid (),
  birth_date date null,
  gender text null,
  bio text null,
  agree_marketing boolean null default false,
  role text null default 'user'::text,
  avatar_img_url text null,
  header_img_url text null,
  custom_user_id text null,
  website_url text[] null,
  public_profile boolean null default true,
  follow_approval boolean null default false,
  like_notification boolean null default true,
  comment_notification boolean null default true,
  follow_notification boolean null default true,
  email_notification boolean null default false,
  hide_bookmark_modal boolean null default false,
  constraint users_pkey primary key (id),
  constraint user_email_key unique (email),
  constraint users_custom_user_id_key unique (custom_user_id)
) TABLESPACE pg_default;